services:
  app:
    image: ghcr.io/modest-human-brands/modest-human-brands:latest
    env_file:
      - .env
    volumes:
      - modest-human-brands_data:/app/.data
    expose:
      - 3000
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  drive:
    image: ghcr.io/modest-human-brands/mdrive:latest
    env_file:
      - .env
    volumes:
      - mdrive-data:/app/data
      - mdrive-static:/app/static
    expose:
      - 3111 # REST API
      - 3112 # Stream
      - 49134 # WebSocket bridge
    ports:
      - '9000:9000/udp'
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

  caddy:
    image: caddy:alpine
    restart: on-failure:3
    ports:
      - 8080
    volumes:
      - /root/modest-human-brands/mdrive/Caddyfile:/etc/caddy/Caddyfile
      - mdrive-static:/srv/static
    networks:
      - internal

volumes:
  modest-human-brands_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/.data
  mdrive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/data
  mdrive-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/static

networks:
  internal:
    driver: overlay
